rb1:
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 50.0

#rb1_base:
  joint_left_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_left_wheel
    pid: {p: 200.0, i: 0.01, d: 10.0}

  joint_right_velocity_controller:
    type: effort_controllers/JointEffortController
    joint: joint_right_wheel
    pid: {p: 200.0, i: 0.01, d: 10.0}

  j1_torso_controller:
    type: effort_controllers/JointPositionController    
    joint: j1_torso
    pid: {p: 15000.0, i: 1.0, d: 200.0}

  j1_head_controller:
    type: effort_controllers/JointPositionController
    joint: j1_head
    pid: {p: 100.0, i: 0.01, d: 50.0}

  j2_head_controller:
    type: effort_controllers/JointPositionController
    joint: j2_head
    pid: {p: 100.0, i: 0.01, d: 50.0}

#rb1_arm:
  j1_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: j1
    pid: 
      p: 10.0
      i: 380
      i_clamp: 100.0

  j2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: j2
    pid: 
      p: 0.0
      i: 380
      i_clamp: 100.0
  
  j3_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: j3
    pid: 
      p: 0.0
      i: 380
      i_clamp: 100.0

  j4_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: j4
    pid: 
      p: 100.0
      i: 20
      i_clamp: 100.0

  j5_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: 
      p: 100.0
      i: 20
      i_clamp: 100.0

  j6_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: j6
    pid: 
      p: 100.0
      i: 20
      i_clamp: 100.0

  j7_velocity_controller:
    type: effort_controllers/JointPositionController
    joint: j7
    pid: 
      p: 100.0
      i: 20
      i_clamp: 100.0
    
  jg2_velocity_controller:
    type: effort_controllers/JointVelocityController
    joint: jg2
    pid: 
      p: 100.0
      i: 20
      i_clamp: 100.0


