rb1_arm:

  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 100.0, i: 10.0, d: 10.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 500.0, i: 500.0, d: 250.0}
  
  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 100.0, i: 0.1, d: 10.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 100.0, i: 0.1, d: 10.0}

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 100.0, i: 0.1, d: 10.0}

  j6_position_controller:
    type: effort_controllers/JointPositionController
    joint: j6
    pid: {p: 100.0, i: 0.1, d: 10.0}

  j7_position_controller:
    type: effort_controllers/JointPositionController
    joint: j7
    pid: {p: 100.0, i: 0.1, d: 10.0}

#  gripper_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: j1_gripper
#    pid: {p: 100.0, i: 0.1, d: 10.0}

  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 100.0
