rb1:
  joint_read_state_controller:
    type: joint_state_controller/JointStateController 
    publish_rate: 50.0

  j1_position_controller:
    type: effort_controllers/JointPositionController
    joint: j1
    pid: {p: 500.0, i: 20.0, d: 5.0}

  j2_position_controller:
    type: effort_controllers/JointPositionController
    joint: j2
    pid: {p: 700.0, i: 30.0, d: 5.0}
  
  j3_position_controller:
    type: effort_controllers/JointPositionController
    joint: j3
    pid: {p: 800.0, i: 30, d: 0.0}

  j4_position_controller:
    type: effort_controllers/JointPositionController
    joint: j4
    pid: {p: 200.0, i: 20, d: 5.0}

  j5_position_controller:
    type: effort_controllers/JointPositionController
    joint: j5
    pid: {p: 400.0, i: 15, d: 0.0}

  j6_position_controller:
    type: effort_controllers/JointPositionController
    joint: j6
    pid: {p: 800.0, i: 10, d: 1.0}

  j7_position_controller:
    type: effort_controllers/JointPositionController
    joint: j7
    pid: {p: 7000.0, i: 200, d: 1.0}
    
  jg2_position_controller:
    type: effort_controllers/JointPositionController
    joint: jg2
    pid: {p: 100.0, i: 0.1, d: 0.1}


#  gripper_position_controller:
#    type: effort_controllers/JointPositionController
#    joint: j1_gripper
#    pid: {p: 100.0, i: 0.1, d: 10.0}


