# Configs the mapping of joints with real devices
# Define the different types of interfaces
types: [ gazebo_position]

groups: { 
 arm_j1: { name: arm_j1, type: gazebo_position, joints: [mico_joint_1], command_topic: /rb1/j1_position_controller/command},
 arm_j2: { name: arm_j2, type: gazebo_position, joints: [mico_joint_2], command_topic: /rb1/j2_position_controller/command},
 arm_j3: { name: arm_j3, type: gazebo_position, joints: [mico_joint_3], command_topic: /rb1/j3_position_controller/command},
 arm_j4: { name: arm_j4, type: gazebo_position, joints: [mico_joint_4], command_topic: /rb1/j4_position_controller/command},
 arm_j5: { name: arm_j5, type: gazebo_position, joints: [mico_joint_5], command_topic: /rb1/j5_position_controller/command},
 arm_j6: { name: arm_j6, type: gazebo_position, joints: [mico_joint_6], command_topic: /rb1/jhand_position_controller/command},
 torso_j1: { name: torso_j1, type: gazebo_position, joints: [j1_torso], command_topic: /rb1/j1_torso_controller/command},
 gripper_j1: { name: gripper_j1, type: gazebo_position, joints: [mico_joint_finger_1], command_topic: /rb1/jf1_position_controller/command},
 gripper_j2: { name: gripper_j2, type: gazebo_position, joints: [mico_joint_finger_2], command_topic: /rb1/jf2_position_controller/command},
 gripper_j3: { name: gripper_j3, type: gazebo_position, joints: [mico_joint_finger_3], command_topic: /rb1/jf3_position_controller/command}, 
 head_j1: { name: head_j1, type: gazebo_position, joints: [j1_head], command_topic: /rb1/j1_head_controller/command},
 head_j2: { name: head_j2, type: gazebo_position, joints: [j2_head], command_topic: /rb1/j2_head_controller/command}
}
